compile time errors solved, current issue:
LYZJU2019/rafka pull request #2
Opened 2024-11-17 22:57 UTC by wyattgill9

Failed to send message to consumer 'consumer_1': SendError { .. }
Error: Broker error: Dispatch failed: Failed to send to consumer 'consumer_1': channel closed

2024-11-17 23:07 UTC, LYZJU2019 requested changes
Overall LGTM. Left some comments. Good job!

2024-11-17 23:07 UTC, LYZJU2019 commented on .vscode/settings.json
I think we should not push `.vscode` folder to git.

2024-11-17 23:07 UTC, LYZJU2019 commented on crates/consumer/src/simple_consumer.rs
Why do we need a `sender` in `Consumer`?

2024-11-18 00:05 UTC, wyattgill9 commented on .vscode/settings.json
yes!

2024-11-18 00:30 UTC, LYZJU2019 approved these changes
LGTM

2024-11-18 00:31 UTC, merged